### ISSUE TITLE
Getting Started documentation is lacking

### ISSUE THREAD

**Issue by joehays** [edrevo/dockerfile-plus#1]
I'm not sure what I need to do to get started. Do I have to clone the repo somewhere? Do I have to "install" dockerfile-plus so docker will recognize the 'syntax' command? Please elaborate on how to get dockerfile-plus properly build/configured so the rest of the Getting Started example works. 

Thanks.

**Comment by edrevo** [comment]
You just need to be using Docker 20.10+. Just that! The `# syntax` command is pre-bundled with the latest Docker, so you can just add that line and start using `INCLUDE+`.

I'll update the getting started section with a step by step tutorial, to make it more explicit. Thanks for the feedback.

**Comment by joehays** [comment]
Here's what I'm getting.

```
joehays@scylla:~/dev/wisard/src/wisard-dev-ops/src/docker-bionic$ docker -v
Docker version 20.10.3, build 48d30b5
joehays@scylla:~/dev/wisard/src/wisard-dev-ops/src/docker-bionic$ cat Dockerfile-test 
# syntax = edrevo/dockerfile-plus

FROM alpine

INCLUDE+ Dockerfile.common

ENTRYPOINT[ "mybin" ]
 
joehays@scylla:~/dev/wisard/src/wisard-dev-ops/src/docker-bionic$ cat Dockerfile.common 
RUN echo "Hello World"
joehays@scylla:~/dev/wisard/src/wisard-dev-ops/src/docker-bionic$ docker build -f Dockerfile-test .
Sending build context to Docker daemon   21.5kB
Error response from daemon: dockerfile parse error line 5: unknown instruction: INCLUDE+
joehays@scylla:~/dev/wisard/src/wisard-dev-ops/src/docker-bionic$ 
```

The version is satisfied. The Dockerfile has the correct first line and INCLUDE+ command, yet it's not being recognized. 

Thoughts?

**Comment by edrevo** [comment]
I'll look into it. Can you `export DOCKER_BUILDKIT=1` and try again?

**Comment by TobiasSchaffner** [comment]
I am running into the same Issue and it persists with export DOCKER_BUILDKIT=1 set.

**Comment by jreades** [comment]
Using ZSH on Big Sur with Docker 3.1.0 I _can_ get this to run with:
```bash
export DOCKER_BUILDKIT=1
docker build ...
```
The main Docker file is then INCLUDE(+)ing a different Dockerfile in the same directory as I'm trying to create a multi-stage build to simplify Python package management and JupyterLab extension compilation.

**Comment by mkastner** [comment]
```bash
export DOCKER_BUILDKIT=1
```

doesn't work for me to get INCLUDE+ going on MacOS Big Sur Version 11.2.1 with Docker Engine 20.10.2

Are there other options to get it going?

**Comment by jreades** [comment]
I'm also on 11.2.1 with Engine 20.10.2 and no issues. Just to check, the first line in your Dockerfile is definitely:
```
# syntax = edrevo/dockerfile-plus
```
So it's the `export` _and_ the `syntax` statement to get `INCLUDE+` working. If that's still not working for you then I wonder if our shell environments are somehow different since I now have a 3-stage build that uses INCLUDE+ without a hitch.

**Comment by mkastner** [comment]
@jreades Seriously, I'm applying it exactly as prescribed:

I'm exporting DOCKER_BUILDKIT=1 to my env. ```echo $DOCKER_BUILDKIT``` returns **1**.  I fact, just to make sure, I've set the export DOCKER_BUILDKIT=1 again in my shell-script which starts my docker-compose.up.

Maybe then there's a problem with running dockerfile-plus inside docker-compose directives with build. I don't know ...

Anyway, here's my setup:

**Dockerfile.base**

```bash
# joint settings for development, production and staging
FROM mariadb:10.3
```

**Dockerfile.production**

```bash
# syntax = edrevo/dockerfile-plus
INCLUDE+ Dockerfile.base
# add more production specific settings when needed
```

**Dockerfile.development**

```
# syntax = edrevo/dockerfile-plus
INCLUDE+ Dockerfile.base
# add more production specific settings when needed
```

**docker-compose.base.yml**

```bash
version: "3.8"

services:
  mariadb:
    container_name: my_mariadb
    build:
      context: .
    volumes:
      - ./../../databases/mysql-my:/var/lib/mysql
      - ~/.ssh:/root/.ssh
    logging:
      driver: local
      ports:
        - "3306:3306"
    restart: on-failure
    networks:
      - backend
networks:
  backend:
    driver: $DOCKER_NETWORKS_DRIVER
```

**docker-compose.production.yml**

```bash
services:
  mariadb:
    build:
      dockerfile: Dockerfile.production
    environment:
      PRODUCTION: "true"
      DEBUG: "true"
      MYSQL_ROOT_PASSWORD: $DBPASSWORD_PRODUCTION
      MYSQL_DATABASE: $DBNAME_PRODUCTION
      MYSQL_USER: $DBUSER_PRODUCTION
      MYSQL_PASSWORD: $DBPASSWORD_PRODUCTION
```

**docker-compose.development.yml**

```
services:
  mariadb:
    build:
      dockerfile: Dockerfile.development
    environment:
      DEVELOPMENT: "true"
      INFO: "true"
      MYSQL_ROOT_PASSWORD: $DBPASSWORD_DEVELOPMENT
      MYSQL_DATABASE: $DBNAME_DEVELOPMENT
      MYSQL_USER: $DBUSER_DEVELOPMENT
      MYSQL_PASSWORD: $DBPASSWORD_DEVELOPMENT
```

This starts up properly on my development machine when running. As I already mentioned is already set, but just to make sure, I'm setting it again in the startup script:

docker.development.sh

```bash
export DOCKER_BUILDKIT=1
docker-compose -f docker-compose.base.yml -f docker-compose.development.yml up
```

**Comment by jreades** [comment]
This would be one for Ximo to answer then as my use case is much simpler:

Dockerfile.master has three included Dockerfiles (python.install, python.update, and jupyterlab.extensions) and I'm just doing a simple build
```
docker build --tag jreades/XXX --compress --file ./docker/Dockerfile.master .
```
And my `.zshrc` file contains:
```
export DOCKER_BUILDKIT=1
```
And the master file:
```
# syntax = edrevo/dockerfile-plus
# various bits and bobs

FROM jupyter/minimal-notebook:016833b15ceb

#--- Python ---#
INCLUDE+ ./docker/python.install
INCLUDE+ ./docker/python.update

...
```

**Comment by edrevo** [comment]
Sorry for the delay. I have been busy with other projects.

I have updated the README so that everyone exports both environment variables (the docker one and the docker-compose one). This should not be necessary in newer installations of Docker, but it doesn't hurt adding it to the guide.

@joehays @fjahn @TobiasSchaffner, were you by any chance using docker-compose? you will need to `export COMPOSE_DOCKER_CLI_BUILD=1` as pointed out by @mkastner

**Comment by joehays** [comment]
> I have updated the README so that everyone exports both environment variables (the docker one and the docker-compose one). This should not be necessary in newer installations of Docker, but it doesn't hurt adding it to the guide.
> 
> @joehays @fjahn @TobiasSchaffner, were you by any chance using docker-compose? you will need to `export COMPOSE_DOCKER_CLI_BUILD=1` as pointed out by @mkastner

No docker-compose. defining,

`DOCKER_BUILDKIT=1`

solved the problem. 

Thank you!
