### ISSUE TITLE
How to use relative or absolute paths with INCLUDE+

### ISSUE THREAD

**Issue by joehays** [edrevo/dockerfile-plus#3]
I get the following error when the 'Dockerfile.common' is not in the same directory. 

`failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Code(128) desc = Could not read file " ../../../mbKinDyn-algos/docker.requirements". Remember that the file path is relative to the build context, not the Dockerfile path.`

I also tried using an absolute path and got the same error. 

The third test was to make the CWD a parent of both the Dockerfile folder and the 'docker.requirements' folder and then I used a relative path to both the Dockerfile and 'docker.requirements' from the parent folder. This produced the same error.

I have multiple git repositories that are related to the Docker container that I'm building. Each repository has a 'docker.requirements' file that documents the dependencies that it needs backed into the docker image/container. So, I need the ability to keep these INSERT+ files in locations other than the main Dockerfile.

Thoughts?

**Comment by edrevo** [comment]
Can you share what's the file layout and the docker build command you are using?

**Comment by joehays** [comment]
It works correctly. My understanding of the build context was lacking...

say I have the following folder structure,

```
~/tmp
          sub/
                Dockerfile
          sub2/
                Dockerfile.common
```
                
if I'm in ~/tmp/sub then I can successfully build with the following

`user:~/tmp/sub$docker build .. -f ./Dockerfile --no-cache -t test_include_plus`

where Dockerfile is,

```
# syntax = edrevo/dockerfile-plus

FROM alpine

INCLUDE+ ./sub2/Dockerfile.common

ENTRYPOINT [ "mybin" ]
```
